=== WeMakeMachines/loomse/schemas/loomse-story.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Loomse story",
  "description": "This document outlines the correct formatting for the scripted story",
  "properties": {
    "shortName": { "type": "string" },
    "longName": { "type": "string" },
    "author": { "type": "string" },
    "description": { "type": "string" },
    "firstScene": { "type": "string" },
    "language": { "type": "string" },
    "scenes": {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/ScriptedScene" }
    }
  },
  "required": ["firstScene", "scenes"],
  "definitions": {
    "ScriptedScene": {
      "type": "object",
      "properties": {
        "longName": { "type": "string" },
        "video": { "$ref": "#/definitions/ScriptedVideo" },
        "events": {
          "type": "array",
          "items": { "$ref": "#/definitions/ScriptedEvent" }
        }
      },
      "required": ["video", "events"]
    },
    "ScriptedVideo": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "object",
          "properties": {
            "mp4": { "type": "string" },
            "ogg": { "type": "string" },
            "webm": { "type": "string" }
          },
          "additionalProperties": false
        },
        "autoplay": { "type": "boolean" },
        "controls": { "type": "boolean" },
        "loop": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "object",
              "properties": {
                "in": { "type": "number" },
                "out": { "type": "number" }
              },
              "required": ["in", "out"]
            }
          ]
        },
        "muted": { "type": "boolean" },
        "subtitles": { "type": "string" }
      }
    },
    "ScriptedEvent": {
      "type": "object",
      "properties": {
        "pluginName": { "type": "string" },
        "in": { "type": "number" },
        "out": { "type": "number" },
        "payload": {}
      },
      "required": ["in", "out"]
    }
  }
}

=== WeMakeMachines/loomse/docs/loomse-story-example.json
{
  "shortName": "LoomSE Template Script",
  "longName": "",
  "author": "Franco Speziali",
  "description": "A sample script to demonstrate the capabilities of Loom",
  "firstScene": "shore",
  "scenes": {
    "shore": {
      "longName": "",
      "video": {
        "autoplay": true,
        "muted": true,
        "subtitles": "subtitles.srt",
        "sources": {
          "mp4": "assets/mp4/shore.mp4"
        }
      },
      "events": [
        {
          "pluginName": "showContentWithLogo",
          "in": 0,
          "out": 11,
          "payload": {
            "text": "Loom Story Engine"
          }
        },
        {
          "pluginName": "skipToScene",
          "in": 11,
          "out": 11,
          "payload": {
            "nextScene": "dolphins"
          }
        }
      ]
    },
    "dolphins": {
      "longName": "",
      "video": {
        "autoplay": true,
        "muted": true,
        "sources": {
          "mp4": "assets/mp4/dolphins.mp4"
        }
      },
      "events": [
        {
          "pluginName": "showContent",
          "in": 0.5,
          "out": 4,
          "payload": {
            "text": "This text is not part of the video file"
          }
        },
        {
          "pluginName": "showContent",
          "in": 4.5,
          "out": 9.5,
          "payload": {
            "text": "It is generated from an event"
          }
        },
        {
          "pluginName": "skipToScene",
          "in": 10,
          "out": 10,
          "payload": {
            "nextScene": "shore"
          }
        }
      ]
    }
  }
}

=== WeMakeMachines/loomse/docs/script-example.json
{
  "shortName": "LoomSE Template Script",
  "longName": "",
  "author": "Franco Speziali",
  "description": "A sample script to demonstrate the capabilities of Loom",
  "firstScene": "farmhack",
  "language": "en_GB",
  "scenes": {
    "farmhack": {
      "longName": "",
      "video": {
        "autoplay": true,
        "muted": true,
        "sources": {
          "mp4": "assets/videos/farmhack-graph-demo.mp4"
        }
      },
      "events": [
        {
          "group": "showContentWithLogo",
          "in": 0,
          "out": 11000,
          "payload": {
            "text": "Loom Story Engine"
          }
        },
        {
          "group": "skipTo",
          "in": 11000,
          "out": 11000,
          "payload": {
            "nextScene": "rideInCar"
          }
        }
      ]
    },
    "rideInCar": {
      "longName": "",
      "video": {
        "autoplay": true,
        "muted": true,
        "sources": {
          "mp4": "assets/videos/ride-in-car.mp4"
        }
      },
      "events": [
        {
          "group": "showContent",
          "in": 500,
          "out": 4000,
          "payload": {
            "text": "This text is not part of the video file"
          }
        },
        {
          "group": "showContent",
          "in": 4500,
          "out": 9500,
          "payload": {
            "text": "It is generated from an event"
          }
        },
        {
          "group": "skipTo",
          "in": 10000,
          "out": 10000,
          "payload": {
            "nextScene": "farmhack"
          }
        }
      ]
    }
  }
}

=== WeMakeMachines/loomse/docs/script-template.json
{
  "shortName": "LoomSE Sample Script",
  "longName": "",
  "author": "You",
  "description": "",
  "firstScene": "intro",
  "language": "en_GB",
  "scenes": {
    "intro": {
      "longName": "",
      "video": {
        "autoplay": true,
        "muted": true,
        "sources": {
          "mp4": ""
        }
      },
      "events": []
    }
  }
}
